version: '2'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - dev.env
    ports:
      - 7777:7777
    volumes:
      - .:/home/node/code
    links:
      - mongo
  mongo:
    image: mongo:3
    volumes:
      - mongodata:/data/db
    ports:
      - 27018:27017
volumes:
  mongodata:
