FROM node:6.10.3-alpine

# this is user comes free with the node alpine image
USER node

ENV HOME /home/node
ENV CODE $HOME/code

RUN mkdir $HOME/.node

RUN mkdir -p $CODE

WORKDIR $CODE


CMD ["npm", "start"]
